packages:
    - docs

sharedWorkspaceLockfile: false

ignoredBuiltDependencies:
    - "@sap/hana-client"
    - es5-ext
    - libpq
    - oracledb
    - protobufjs

onlyBuiltDependencies:
    - better-sqlite3
    - sqlite3

minimumReleaseAge: 1440
