import "reflect-metadata"
import { expect } from "chai"
import type { DataSource } from "../../../../src"
import { EntitySchema } from "../../../../src"
import {
    closeTestingConnections,
    createTestingConnections,
} from "../../../utils/test-utils"
import {
    expectNoDropOfName,
    expectSyncIsIdempotent,
    getIndexNames,
} from "./rename-on-naming-change-helpers"

// Shared "new" entity — what the metadata wants after the naming-strategy /
// renamed / custom-name change. Seed flows drive the DB away from this state
// so the sync reconciler sees drift.
const UserNewNames = new EntitySchema({
    name: "rc_user",
    tableName: "rc_user",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    indices: [{ name: "idx_new", columns: ["email"] }],
    uniques: [{ name: "uq_new", columns: ["email", "tenantId"] }],
})

describe("schema builder > rename on naming change > index", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            entities: [UserNewNames],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    /**
     * Seed: `synchronize()` creates the table with the "new" names; then the
     * index is renamed server-side to the drift target. The next sync sees
     * DB-has-`oldName` / metadata-wants-`idx_new` and exercises the reconciler.
     */
    async function seedIndexUnderOldName(
        dataSource: DataSource,
        oldName: string,
    ): Promise<void> {
        await dataSource.synchronize()
        const qr = dataSource.createQueryRunner()
        try {
            const table = await qr.getTable("rc_user")
            expect(
                table?.indices.some((i) => i.name === "idx_new"),
                `seed expected idx_new on ${dataSource.driver.options.type}`,
            ).to.be.true
            await qr.renameIndex!("rc_user", "idx_new", oldName)
        } finally {
            await qr.release()
        }
    }

    it("custom → different custom: rename, no DROP of old name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedIndexUnderOldName(dataSource, "idx_old")

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "idx_old")

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user")
                expect(names, dataSource.driver.options.type).to.include(
                    "idx_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_old",
                )
            }),
        ))

    it("second sync after renaming drifted index is idempotent", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedIndexUnderOldName(dataSource, "idx_old")
                await dataSource.synchronize()

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})

// Separate suite: the entity has NO explicit index name, so the metadata-side
// name is whatever the driver's naming strategy generates. Drift is still
// introduced by server-side rename to a custom value; reconciler should rename
// back to the autogenerated name.
const UserAutoIndex = new EntitySchema({
    name: "rc_user_auto",
    tableName: "rc_user_auto",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
    },
    indices: [{ columns: ["email"] }],
})

describe("schema builder > rename on naming change > index (auto-named)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            entities: [UserAutoIndex],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("custom → auto: renames a manually-named drift back to the auto hash", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                // What the naming strategy wants.
                const autoName = dataSource.namingStrategy.indexName(
                    "rc_user_auto",
                    ["email"],
                )

                // Seed drift: server-rename the auto-named index to a custom
                // string. After this, DB has "idx_manual_drift" while metadata
                // expects the auto hash.
                const qr = dataSource.createQueryRunner()
                try {
                    const table = await qr.getTable("rc_user_auto")
                    const seedName = table?.indices.find(
                        (i) =>
                            i.columnNames.length === 1 &&
                            i.columnNames[0] === "email",
                    )?.name
                    expect(
                        seedName,
                        `seed expected an auto-named index on email (${dataSource.driver.options.type})`,
                    ).to.equal(autoName)
                    await qr.renameIndex!(
                        "rc_user_auto",
                        autoName,
                        "idx_manual_drift",
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "idx_manual_drift")

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user_auto")
                expect(names, dataSource.driver.options.type).to.include(
                    autoName,
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_manual_drift",
                )
            }),
        ))
})
