import "reflect-metadata"
import { expect } from "chai"
import type { DataSource } from "../../../../src"
import { EntitySchema } from "../../../../src"
import {
    closeTestingConnections,
    createTestingConnections,
} from "../../../utils/test-utils"
import {
    expectNoDropOfName,
    expectSyncIsIdempotent,
} from "./rename-on-naming-change-helpers"

// `renamePrimaryKey` is implemented on dialects that expose the PK as a
// named constraint. MySQL/MariaDB name every PK "PRIMARY" (no identity to
// rename); SAP HANA and SQLite have no native PK rename.
const ENABLED_DRIVERS = ["postgres", "cockroachdb", "mssql", "oracle"] as const

async function getPrimaryKeyName(
    dataSource: DataSource,
    tableName: string,
): Promise<string | undefined> {
    const qr = dataSource.createQueryRunner()
    try {
        const table = await qr.getTable(tableName)
        return table?.columns.find((c) => c.isPrimary)?.primaryKeyConstraintName
    } finally {
        await qr.release()
    }
}

const UserNewPk = new EntitySchema({
    name: "rc_pk_user",
    tableName: "rc_pk_user",
    columns: {
        id: {
            type: Number,
            primary: true,
            primaryKeyConstraintName: "pk_new",
        },
        email: { type: String, nullable: false },
    },
})

describe("schema builder > rename on naming change > primary key", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserNewPk],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    async function seedPrimaryKeyUnderOldName(
        dataSource: DataSource,
        oldName: string,
    ): Promise<void> {
        await dataSource.synchronize()
        const qr = dataSource.createQueryRunner()
        try {
            await qr.renamePrimaryKey!("rc_pk_user", "pk_new", oldName)
        } finally {
            await qr.release()
        }
    }

    it("custom → different custom: rename, no DROP of old name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedPrimaryKeyUnderOldName(dataSource, "pk_old")

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "pk_old")

                await dataSource.synchronize()
                const name = await getPrimaryKeyName(dataSource, "rc_pk_user")
                expect(name, dataSource.driver.options.type).to.equal("pk_new")
            }),
        ))

    it("auto → custom: renames an autogenerated PK name to the explicit metadata name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                const autoName = dataSource.namingStrategy.primaryKeyName(
                    "rc_pk_user",
                    ["id"],
                )
                await seedPrimaryKeyUnderOldName(dataSource, autoName)

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, autoName)

                await dataSource.synchronize()
                const name = await getPrimaryKeyName(dataSource, "rc_pk_user")
                expect(name, dataSource.driver.options.type).to.equal("pk_new")
            }),
        ))

    it("second sync after renaming the primary key is idempotent", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedPrimaryKeyUnderOldName(dataSource, "pk_old")
                await dataSource.synchronize()

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})

// Entity with no explicit `primaryKeyConstraintName` — the metadata-side PK
// name falls back to the naming strategy. The seed flips the auto name to a
// custom string; reconciler should rename it back.
const UserAutoPk = new EntitySchema({
    name: "rc_pk_auto",
    tableName: "rc_pk_auto",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
    },
})

describe("schema builder > rename on naming change > primary key (auto-named)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserAutoPk],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("custom → auto: renames a manually-named PK back to the auto hash", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                const autoName = dataSource.namingStrategy.primaryKeyName(
                    "rc_pk_auto",
                    ["id"],
                )

                const qr = dataSource.createQueryRunner()
                try {
                    // The seed column's `primaryKeyConstraintName` is
                    // undefined whenever the DB name matches the naming
                    // strategy — `loadTables` only populates the field when
                    // it diverges. So the seed passes when the field is
                    // undefined or exactly `autoName`.
                    const seedName = await getPrimaryKeyName(
                        dataSource,
                        "rc_pk_auto",
                    )
                    expect(
                        seedName ?? autoName,
                        `seed expected auto PK name on (id) (${dataSource.driver.options.type})`,
                    ).to.equal(autoName)
                    await qr.renamePrimaryKey!(
                        "rc_pk_auto",
                        autoName,
                        "pk_manual_change",
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "pk_manual_change")

                await dataSource.synchronize()
                // After reconciler renames back to the auto name,
                // `primaryKeyConstraintName` drops to `undefined` again —
                // same reason as above. The rename is considered successful
                // when the DB either reports the auto name explicitly or
                // suppresses it as the default.
                const name = await getPrimaryKeyName(dataSource, "rc_pk_auto")
                expect(
                    name ?? autoName,
                    dataSource.driver.options.type,
                ).to.equal(autoName)
            }),
        ))
})
