import "reflect-metadata"
import { expect } from "chai"
import type { DataSource } from "../../../../src"
import { EntitySchema, TableIndex } from "../../../../src"
import {
    closeTestingConnections,
    createTestingConnections,
} from "../../../utils/test-utils"
import {
    expectNoDropOfName,
    expectSyncIsIdempotent,
    getIndexNames,
} from "./rename-on-naming-change-helpers"

// Shared "new" entity — what the metadata wants after the naming-strategy /
// renamed / custom-name change. Seed flows drive the DB away from this state
// so the sync reconciler sees the name change.
const UserNewNames = new EntitySchema({
    name: "rc_user",
    tableName: "rc_user",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    indices: [{ name: "idx_new", columns: ["email"] }],
    uniques: [{ name: "uq_new", columns: ["email", "tenantId"] }],
})

describe("schema builder > rename on naming change > index", () => {
    let dataSources: DataSource[]

    before(async () => {
        // The seed helper renames the index server-side via `qr.renameIndex`;
        // drivers without that primitive (sqlite family, spanner, mongodb)
        // can't participate. Keep this list aligned with the drivers that
        // implement `renameIndex` in `test/functional/query-runner/rename/
        // rename-index.test.ts`.
        dataSources = await createTestingConnections({
            enabledDrivers: [
                "postgres",
                "cockroachdb",
                "mssql",
                "oracle",
                "mysql",
                "mariadb",
                "sap",
            ],
            entities: [UserNewNames],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    /**
     * Seed: `synchronize()` creates the table with the "new" names; then the
     * index is renamed server-side to the old name. The next sync sees
     * DB-has-`oldName` / metadata-wants-`idx_new` and exercises the reconciler.
     */
    async function seedIndexUnderOldName(
        dataSource: DataSource,
        oldName: string,
    ): Promise<void> {
        await dataSource.synchronize()
        const qr = dataSource.createQueryRunner()
        try {
            const table = await qr.getTable("rc_user")
            expect(
                table?.indices.some((i) => i.name === "idx_new"),
                `seed expected idx_new on ${dataSource.driver.options.type}`,
            ).to.be.true
            await qr.renameIndex!("rc_user", "idx_new", oldName)
        } finally {
            await qr.release()
        }
    }

    it("custom → different custom: rename, no DROP of old name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedIndexUnderOldName(dataSource, "idx_old")

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "idx_old")

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user")
                expect(names, dataSource.driver.options.type).to.include(
                    "idx_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_old",
                )
            }),
        ))

    it("auto → custom: renames an autogenerated-named index to the explicit metadata name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                // DB is seeded under the auto-hashed name the default
                // naming strategy would produce for this column set. Metadata
                // wants the explicit "idx_new" — reconciler should rename
                // the auto hash to "idx_new".
                const autoIndexName = dataSource.namingStrategy.indexName(
                    "rc_user",
                    ["email"],
                )
                await seedIndexUnderOldName(dataSource, autoIndexName)

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, autoIndexName)

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user")
                expect(names, dataSource.driver.options.type).to.include(
                    "idx_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    autoIndexName,
                )
            }),
        ))

    it("second sync after renaming the index is idempotent", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedIndexUnderOldName(dataSource, "idx_old")
                await dataSource.synchronize()

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})

// Separate suite: the entity has NO explicit index name, so the metadata-side
// name is whatever the driver's naming strategy generates. The old name is
// still introduced by server-side rename to a custom value; reconciler should
// rename back to the autogenerated name.
const UserAutoIndex = new EntitySchema({
    name: "rc_user_auto",
    tableName: "rc_user_auto",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
    },
    indices: [{ columns: ["email"] }],
})

describe("schema builder > rename on naming change > index (auto-named)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [
                "postgres",
                "cockroachdb",
                "mssql",
                "oracle",
                "mysql",
                "mariadb",
                "sap",
            ],
            entities: [UserAutoIndex],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("custom → auto: renames a manually-named index back to the auto hash", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                // What the naming strategy wants.
                const autoName = dataSource.namingStrategy.indexName(
                    "rc_user_auto",
                    ["email"],
                )

                // Seed the change: server-rename the auto-named index to a
                // custom string. After this, DB has "idx_manual_change" while
                // metadata expects the auto hash.
                const qr = dataSource.createQueryRunner()
                try {
                    const table = await qr.getTable("rc_user_auto")
                    const seedName = table?.indices.find(
                        (i) =>
                            i.columnNames.length === 1 &&
                            i.columnNames[0] === "email",
                    )?.name
                    expect(
                        seedName,
                        `seed expected an auto-named index on email (${dataSource.driver.options.type})`,
                    ).to.equal(autoName)
                    await qr.renameIndex!(
                        "rc_user_auto",
                        autoName,
                        "idx_manual_change",
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "idx_manual_change")

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user_auto")
                expect(names, dataSource.driver.options.type).to.include(
                    autoName,
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_manual_change",
                )
            }),
        ))
})

// Duplicate-on-db scenario: the database ends up with two structurally
// identical indexes (same column set) under different names while metadata
// declares only one. The reconciler should pair one of them with the
// metadata name via rename, and leave the other for the follow-up drop pass.
const UserDuplicateIndex = new EntitySchema({
    name: "rc_user_dup",
    tableName: "rc_user_dup",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
    },
    indices: [{ name: "idx_new", columns: ["email"] }],
})

describe("schema builder > rename on naming change > index (db duplicates)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [
                "postgres",
                "cockroachdb",
                "mssql",
                "oracle",
                "mysql",
                "mariadb",
                "sap",
            ],
            entities: [UserDuplicateIndex],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("renames one duplicate to the metadata name and drops the other", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                // Rename the metadata-named index out of the way, then add
                // a second structurally-identical index. After this, DB has
                // [idx_old1, idx_old2] both on (email), metadata has idx_new.
                const qr = dataSource.createQueryRunner()
                try {
                    await qr.renameIndex!("rc_user_dup", "idx_new", "idx_old1")
                    await qr.createIndex(
                        "rc_user_dup",
                        new TableIndex({
                            name: "idx_old2",
                            columnNames: ["email"],
                        }),
                    )
                } finally {
                    await qr.release()
                }

                // Reconciler sorts remaining DB entries alphabetically and
                // pairs with metadata, so idx_old1 becomes idx_new and
                // idx_old2 is left for the drop pass.
                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "idx_old1")

                await dataSource.synchronize()
                const names = await getIndexNames(dataSource, "rc_user_dup")
                expect(names, dataSource.driver.options.type).to.include(
                    "idx_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_old1",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "idx_old2",
                )

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})
