import "reflect-metadata"
import { expect } from "chai"
import type { DataSource } from "../../../../src"
import { EntitySchema, TableUnique } from "../../../../src"
import {
    closeTestingConnections,
    createTestingConnections,
} from "../../../utils/test-utils"
import {
    expectNoDropOfName,
    expectSyncIsIdempotent,
    getUniqueNames,
} from "./rename-on-naming-change-helpers"

// `renameUniqueConstraint` is only implemented on drivers where uniques are a
// distinct catalog object. MySQL/MariaDB and SAP HANA model uniques as
// indexes — those are covered by the rename-index suite instead.
const ENABLED_DRIVERS = ["postgres", "cockroachdb", "mssql", "oracle"] as const

const UserNewNames = new EntitySchema({
    name: "rc_uq_user",
    tableName: "rc_uq_user",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    uniques: [{ name: "uq_new", columns: ["email", "tenantId"] }],
})

describe("schema builder > rename on naming change > unique", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserNewNames],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    async function seedUniqueUnderOldName(
        dataSource: DataSource,
        oldName: string,
    ): Promise<void> {
        await dataSource.synchronize()
        const qr = dataSource.createQueryRunner()
        try {
            const table = await qr.getTable("rc_uq_user")
            expect(
                table?.uniques.some((u) => u.name === "uq_new"),
                `seed expected uq_new on ${dataSource.driver.options.type}`,
            ).to.be.true
            await qr.renameUniqueConstraint!("rc_uq_user", "uq_new", oldName)
        } finally {
            await qr.release()
        }
    }

    it("custom → different custom: rename, no DROP of old name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedUniqueUnderOldName(dataSource, "uq_old")

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "uq_old")

                await dataSource.synchronize()
                const names = await getUniqueNames(dataSource, "rc_uq_user")
                expect(names, dataSource.driver.options.type).to.include(
                    "uq_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "uq_old",
                )
            }),
        ))

    it("auto → custom: renames an autogenerated-named unique to the explicit metadata name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                const autoName = dataSource.namingStrategy.uniqueConstraintName(
                    "rc_uq_user",
                    ["email", "tenantId"],
                )
                await seedUniqueUnderOldName(dataSource, autoName)

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, autoName)

                await dataSource.synchronize()
                const names = await getUniqueNames(dataSource, "rc_uq_user")
                expect(names, dataSource.driver.options.type).to.include(
                    "uq_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    autoName,
                )
            }),
        ))

    it("second sync after renaming the unique is idempotent", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedUniqueUnderOldName(dataSource, "uq_old")
                await dataSource.synchronize()

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})

const UserAutoUnique = new EntitySchema({
    name: "rc_uq_auto",
    tableName: "rc_uq_auto",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    uniques: [{ columns: ["email", "tenantId"] }],
})

describe("schema builder > rename on naming change > unique (auto-named)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserAutoUnique],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("custom → auto: renames a manually-named unique back to the auto hash", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                const autoName = dataSource.namingStrategy.uniqueConstraintName(
                    "rc_uq_auto",
                    ["email", "tenantId"],
                )

                const qr = dataSource.createQueryRunner()
                try {
                    const table = await qr.getTable("rc_uq_auto")
                    const seedName = table?.uniques.find(
                        (u) =>
                            u.columnNames.length === 2 &&
                            u.columnNames.includes("email") &&
                            u.columnNames.includes("tenantId"),
                    )?.name
                    expect(
                        seedName,
                        `seed expected an auto-named unique on (email, tenantId) (${dataSource.driver.options.type})`,
                    ).to.equal(autoName)
                    await qr.renameUniqueConstraint!(
                        "rc_uq_auto",
                        autoName,
                        "uq_manual_change",
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "uq_manual_change")

                await dataSource.synchronize()
                const names = await getUniqueNames(dataSource, "rc_uq_auto")
                expect(names, dataSource.driver.options.type).to.include(
                    autoName,
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "uq_manual_change",
                )
            }),
        ))
})

// Reordered-columns scenario: authored column order is part of the structural
// signature, so swapping the order must trigger drop+create, not rename.
const UserReorderedV1 = new EntitySchema({
    name: "rc_uq_reord",
    tableName: "rc_uq_reord",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    uniques: [{ name: "uq_cols", columns: ["email", "tenantId"] }],
})

const UserReorderedV2 = new EntitySchema({
    name: "rc_uq_reord",
    tableName: "rc_uq_reord",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    uniques: [{ name: "uq_cols", columns: ["tenantId", "email"] }],
})

describe("schema builder > rename on naming change > unique (reordered columns)", () => {
    it("reordered column list triggers drop + create, not rename", async () => {
        const firstRound = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserReorderedV1],
            schemaCreate: false,
            dropSchema: true,
        })
        try {
            await Promise.all(
                firstRound.map((dataSource) => dataSource.synchronize()),
            )
        } finally {
            await closeTestingConnections(firstRound)
        }

        const secondRound = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserReorderedV2],
            schemaCreate: false,
            dropSchema: false,
        })
        try {
            await Promise.all(
                secondRound.map(async (dataSource) => {
                    const driverType = dataSource.driver.options.type

                    const log = await dataSource.driver
                        .createSchemaBuilder()
                        .log()
                    const sql = log.upQueries.map((q) => q.query).join(" | ")
                    expect(sql, driverType).to.match(
                        /DROP[^|]*uq_cols/i,
                        "expected a DROP of uq_cols before the recreate",
                    )

                    await dataSource.synchronize()

                    const qr = dataSource.createQueryRunner()
                    try {
                        const table = await qr.getTable("rc_uq_reord")
                        const uq = table?.uniques.find(
                            (u) => u.name === "uq_cols",
                        )
                        expect(uq?.columnNames, driverType).to.deep.equal([
                            "tenantId",
                            "email",
                        ])
                    } finally {
                        await qr.release()
                    }
                }),
            )
        } finally {
            await closeTestingConnections(secondRound)
        }
    })
})

// Duplicate-on-db scenario: the database ends up with two structurally
// identical uniques under different names while metadata declares only one.
const UserDuplicateUnique = new EntitySchema({
    name: "rc_uq_dup",
    tableName: "rc_uq_dup",
    columns: {
        id: { type: Number, primary: true },
        email: { type: String, nullable: false },
        tenantId: { type: Number, nullable: false },
    },
    uniques: [{ name: "uq_new", columns: ["email", "tenantId"] }],
})

describe("schema builder > rename on naming change > unique (db duplicates)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [UserDuplicateUnique],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("renames one duplicate to the metadata name and drops the other", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                const qr = dataSource.createQueryRunner()
                try {
                    await qr.renameUniqueConstraint!(
                        "rc_uq_dup",
                        "uq_new",
                        "uq_old1",
                    )
                    await qr.createUniqueConstraint(
                        "rc_uq_dup",
                        new TableUnique({
                            name: "uq_old2",
                            columnNames: ["email", "tenantId"],
                        }),
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "uq_old1")

                await dataSource.synchronize()
                const names = await getUniqueNames(dataSource, "rc_uq_dup")
                expect(names, dataSource.driver.options.type).to.include(
                    "uq_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "uq_old1",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "uq_old2",
                )

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})
