import "reflect-metadata"
import { expect } from "chai"
import type { DataSource } from "../../../../src"
import { EntitySchema, TableForeignKey } from "../../../../src"
import {
    closeTestingConnections,
    createTestingConnections,
} from "../../../utils/test-utils"
import {
    expectNoDropOfName,
    expectSyncIsIdempotent,
} from "./rename-on-naming-change-helpers"

// `renameForeignKey` is implemented on dialects where FKs are renameable
// constraints. MySQL/MariaDB have no native FK rename; SAP HANA and SQLite
// likewise fall back to drop/create via the default path.
const ENABLED_DRIVERS = ["postgres", "cockroachdb", "mssql", "oracle"] as const

async function getForeignKeyNames(
    dataSource: DataSource,
    tableName: string,
): Promise<string[]> {
    const qr = dataSource.createQueryRunner()
    try {
        const table = await qr.getTable(tableName)
        return table?.foreignKeys.map((f) => f.name ?? "") ?? []
    } finally {
        await qr.release()
    }
}

const Parent = new EntitySchema({
    name: "rc_fk_parent",
    tableName: "rc_fk_parent",
    columns: {
        id: { type: Number, primary: true },
    },
})

const ChildNewFk = new EntitySchema<any>({
    name: "rc_fk_child",
    tableName: "rc_fk_child",
    columns: {
        id: { type: Number, primary: true },
        parentId: { type: Number, nullable: false },
    },
    relations: {
        parent: {
            type: "many-to-one",
            target: "rc_fk_parent",
            joinColumn: {
                name: "parentId",
                referencedColumnName: "id",
                foreignKeyConstraintName: "fk_new",
            },
        },
    },
})

describe("schema builder > rename on naming change > foreign key", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [Parent, ChildNewFk],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    async function seedForeignKeyUnderOldName(
        dataSource: DataSource,
        oldName: string,
    ): Promise<void> {
        await dataSource.synchronize()
        const qr = dataSource.createQueryRunner()
        try {
            const table = await qr.getTable("rc_fk_child")
            expect(
                table?.foreignKeys.some((f) => f.name === "fk_new"),
                `seed expected fk_new on ${dataSource.driver.options.type}`,
            ).to.be.true
            await qr.renameForeignKey!("rc_fk_child", "fk_new", oldName)
        } finally {
            await qr.release()
        }
    }

    it("custom → different custom: rename, no DROP of old name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedForeignKeyUnderOldName(dataSource, "fk_old")

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "fk_old")

                await dataSource.synchronize()
                const names = await getForeignKeyNames(
                    dataSource,
                    "rc_fk_child",
                )
                expect(names, dataSource.driver.options.type).to.include(
                    "fk_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "fk_old",
                )
            }),
        ))

    it("auto → custom: renames an autogenerated-named FK to the explicit metadata name", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                const autoName = dataSource.namingStrategy.foreignKeyName(
                    "rc_fk_child",
                    ["parentId"],
                    "rc_fk_parent",
                    ["id"],
                )
                await seedForeignKeyUnderOldName(dataSource, autoName)

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, autoName)

                await dataSource.synchronize()
                const names = await getForeignKeyNames(
                    dataSource,
                    "rc_fk_child",
                )
                expect(names, dataSource.driver.options.type).to.include(
                    "fk_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    autoName,
                )
            }),
        ))

    it("second sync after renaming the foreign key is idempotent", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await seedForeignKeyUnderOldName(dataSource, "fk_old")
                await dataSource.synchronize()

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})

// Child entity with no explicit `foreignKeyConstraintName` — metadata-side FK
// name comes from the naming strategy. The seed flips the auto name to a
// custom string; reconciler should rename it back.
const ChildAutoFk = new EntitySchema<any>({
    name: "rc_fk_auto_child",
    tableName: "rc_fk_auto_child",
    columns: {
        id: { type: Number, primary: true },
        parentId: { type: Number, nullable: false },
    },
    relations: {
        parent: {
            type: "many-to-one",
            target: "rc_fk_auto_parent",
            joinColumn: {
                name: "parentId",
                referencedColumnName: "id",
            },
        },
    },
})

const ParentAuto = new EntitySchema({
    name: "rc_fk_auto_parent",
    tableName: "rc_fk_auto_parent",
    columns: {
        id: { type: Number, primary: true },
    },
})

describe("schema builder > rename on naming change > foreign key (auto-named)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [ParentAuto, ChildAutoFk],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("custom → auto: renames a manually-named FK back to the auto hash", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                const autoName = dataSource.namingStrategy.foreignKeyName(
                    "rc_fk_auto_child",
                    ["parentId"],
                    "rc_fk_auto_parent",
                    ["id"],
                )

                const qr = dataSource.createQueryRunner()
                try {
                    const table = await qr.getTable("rc_fk_auto_child")
                    const seedName = table?.foreignKeys.find((f) =>
                        f.columnNames.includes("parentId"),
                    )?.name
                    expect(
                        seedName,
                        `seed expected auto FK name on parentId (${dataSource.driver.options.type})`,
                    ).to.equal(autoName)
                    await qr.renameForeignKey!(
                        "rc_fk_auto_child",
                        autoName,
                        "fk_manual_change",
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "fk_manual_change")

                await dataSource.synchronize()
                const names = await getForeignKeyNames(
                    dataSource,
                    "rc_fk_auto_child",
                )
                expect(names, dataSource.driver.options.type).to.include(
                    autoName,
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "fk_manual_change",
                )
            }),
        ))
})

// Duplicate-on-db scenario: two FKs pointing at the same target with the same
// local columns, under different names. Metadata declares only one.
const ParentDup = new EntitySchema({
    name: "rc_fk_dup_parent",
    tableName: "rc_fk_dup_parent",
    columns: {
        id: { type: Number, primary: true },
    },
})

const ChildDupFk = new EntitySchema<any>({
    name: "rc_fk_dup_child",
    tableName: "rc_fk_dup_child",
    columns: {
        id: { type: Number, primary: true },
        parentId: { type: Number, nullable: false },
    },
    relations: {
        parent: {
            type: "many-to-one",
            target: "rc_fk_dup_parent",
            joinColumn: {
                name: "parentId",
                referencedColumnName: "id",
                foreignKeyConstraintName: "fk_new",
            },
        },
    },
})

describe("schema builder > rename on naming change > foreign key (db duplicates)", () => {
    let dataSources: DataSource[]

    before(async () => {
        dataSources = await createTestingConnections({
            enabledDrivers: [...ENABLED_DRIVERS],
            entities: [ParentDup, ChildDupFk],
            schemaCreate: false,
            dropSchema: true,
        })
    })

    after(() => closeTestingConnections(dataSources))

    it("renames one duplicate to the metadata name and drops the other", () =>
        Promise.all(
            dataSources.map(async (dataSource) => {
                await dataSource.synchronize()

                const qr = dataSource.createQueryRunner()
                try {
                    await qr.renameForeignKey!(
                        "rc_fk_dup_child",
                        "fk_new",
                        "fk_old1",
                    )
                    await qr.createForeignKey(
                        "rc_fk_dup_child",
                        new TableForeignKey({
                            name: "fk_old2",
                            columnNames: ["parentId"],
                            referencedColumnNames: ["id"],
                            referencedTableName: "rc_fk_dup_parent",
                        }),
                    )
                } finally {
                    await qr.release()
                }

                const log = await dataSource.driver.createSchemaBuilder().log()
                expectNoDropOfName(log.upQueries, "fk_old1")

                await dataSource.synchronize()
                const names = await getForeignKeyNames(
                    dataSource,
                    "rc_fk_dup_child",
                )
                expect(names, dataSource.driver.options.type).to.include(
                    "fk_new",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "fk_old1",
                )
                expect(names, dataSource.driver.options.type).to.not.include(
                    "fk_old2",
                )

                await expectSyncIsIdempotent(dataSource)
            }),
        ))
})
