import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manually defined sidebar with items in a logical order
    tutorialSidebar: [
        "Getting Started",
        "future-of-typeorm",
        {
            type: "category",
            label: "Data Source",
            link: {
                type: "generated-index",
                title: "Data Source",
                description: "Setting up and configuring Data Sources",
            },
            items: [{ type: "autogenerated", dirName: "Data Source" }],
        },
        {
            type: "category",
            label: "Entity",
            link: {
                type: "generated-index",
                title: "Entity",
                description: "Working with TypeORM entities",
            },
            items: [{ type: "autogenerated", dirName: "Entity" }],
        },
        {
            type: "category",
            label: "Relations",
            link: {
                type: "generated-index",
                title: "Relations",
                description: "Managing entity relationships",
            },
            items: [{ type: "autogenerated", dirName: "Relations" }],
        },
        {
            type: "category",
            label: "Working with Entity Manager",
            link: {
                type: "generated-index",
                title: "Working with Entity Manager",
                description: "Using EntityManager to manipulate your entities",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "Working with Entity Manager",
                },
            ],
        },
        {
            type: "category",
            label: "Query Builder",
            link: {
                type: "generated-index",
                title: "Query Builder",
                description: "Creating custom and complex database queries",
            },
            items: [{ type: "autogenerated", dirName: "Query Builder" }],
        },
        "query-runner",
        {
            type: "category",
            label: "Guides",
            link: {
                type: "generated-index",
                title: "Guides",
                description: "Specific guides for common use cases",
            },
            items: [{ type: "autogenerated", dirName: "Guides" }],
        },
        {
            type: "category",
            label: "Advanced Topics",
            link: {
                type: "generated-index",
                title: "Advanced Topics",
                description: "Advanced features and concepts",
            },
            items: [{ type: "autogenerated", dirName: "Advanced Topics" }],
        },
        {
            type: "category",
            label: "Help",
            link: {
                type: "generated-index",
                title: "Help",
                description: "Troubleshooting and support",
            },
            items: [{ type: "autogenerated", dirName: "Help" }],
        },
        "future-of-typeorm",
    ],
}

export default sidebars
