import {CockroachDriver} from "../../driver/cockroachdb/CockroachDriver";
import {OracleDriver} from "../../driver/oracle/OracleDriver";
import {EntityTarget} from "../../common/EntityTarget";
import {QueryRunner} from "../../query-runner/QueryRunner";
import {SqlServerDriver} from "../../driver/sqlserver/SqlServerDriver";
import {PostgresDriver} from "../../driver/postgres/PostgresDriver";
import {DeleteResult} from "../result/DeleteResult";
import {MysqlDriver} from "../../driver/mysql/MysqlDriver";
import {BroadcasterResult} from "../../subscriber/BroadcasterResult";
import { EntitySchema} from "../../index";
import {AuroraDataApiDriver} from "../../driver/aurora-data-api/AuroraDataApiDriver";
import {BetterSqlite3Driver} from "../../driver/better-sqlite3/BetterSqlite3Driver";
import { ModificationQueryBuilder } from "./ModificationQueryBuilder";

/**
 * Allows to build complex sql queries in a fashion way and execute those queries.
 */
export class DeleteQueryBuilder<Entity> extends ModificationQueryBuilder<Entity, DeleteResult> {

    // -------------------------------------------------------------------------
    // Public Methods
    // -------------------------------------------------------------------------

    /**
     * Specifies FROM which entity's table select/update/delete will be executed.
     * Also sets a main string alias of the selection data.
     */
    from<T>(entityTarget: EntityTarget<T>, aliasName?: string): DeleteQueryBuilder<T> {
        entityTarget = entityTarget instanceof EntitySchema ? entityTarget.options.name : entityTarget;
        const mainAlias = this.createFromAlias(entityTarget, aliasName);
        this.expressionMap.setMainAlias(mainAlias);
        return (this as any) as DeleteQueryBuilder<T>;
    }

    // -------------------------------------------------------------------------
    // Protected Implemented Methods
    // -------------------------------------------------------------------------

    /**
     * Creates DELETE expression used to perform query.
     */
    protected createModificationExpression() {
        const tableName = this.getTableName(this.getMainTableName());
        const whereExpression = this.createWhereExpression();
        const returningExpression = this.createReturningExpression();

        if (returningExpression && (this.connection.driver instanceof PostgresDriver || this.connection.driver instanceof CockroachDriver)) {
            return `DELETE FROM ${tableName}${whereExpression} RETURNING ${returningExpression}`;
        } else if (returningExpression !== "" && this.connection.driver instanceof SqlServerDriver) {
            return `DELETE FROM ${tableName} OUTPUT ${returningExpression}${whereExpression}`;
        } else {
            return `DELETE FROM ${tableName}${whereExpression}`;
        }
    }

    /**
     * Executes sql generated by query builder and returns raw database results.
     */
    protected async executeInsideTransaction(queryRunner: QueryRunner): Promise<DeleteResult> {
        const [sql, parameters] = this.getQueryAndParameters();
        const deleteResult = new DeleteResult();
        const result = await queryRunner.query(sql, parameters);

        if (this.connection.driver instanceof MysqlDriver || this.connection.driver instanceof AuroraDataApiDriver) {
            deleteResult.raw = result;
            deleteResult.affected = result.affectedRows;
        } else if (this.connection.driver instanceof SqlServerDriver || this.connection.driver instanceof PostgresDriver || this.connection.driver instanceof CockroachDriver) {
            deleteResult.raw = result[0] ? result[0] : null;
            // don't return 0 because it could confuse. null means that we did not receive this value
            deleteResult.affected = typeof result[1] === "number" ? result[1] : null;
        } else if (this.connection.driver instanceof OracleDriver) {
            deleteResult.affected = result;
        } else if (this.connection.driver instanceof BetterSqlite3Driver) { // only works for better-sqlite3
            deleteResult.raw = result;
            deleteResult.affected = result.changes;
        } else {
            deleteResult.raw = result;
        }

        return deleteResult;
    }

    protected executeBeforeQueryBroadcast(queryRunner: QueryRunner, broadcastResult: BroadcasterResult) {
        queryRunner.broadcaster.broadcastBeforeRemoveEvent(broadcastResult, this.expressionMap.mainAlias!.metadata);
    }

    protected executeAfterQueryBroadcast(queryRunner: QueryRunner, broadcastResult: BroadcasterResult, result: DeleteResult) {
        queryRunner.broadcaster.broadcastAfterRemoveEvent(broadcastResult, this.expressionMap.mainAlias!.metadata);
    }
}
