import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // Manually defined sidebar with items in a logical order
    tutorialSidebar: [
        "Getting Started",
        {
            type: "category",
            label: "Data Source",
            items: [{ type: "autogenerated", dirName: "Data Source" }],
        },
        {
            type: "category",
            label: "Entity",
            items: [{ type: "autogenerated", dirName: "Entity" }],
        },
        {
            type: "category",
            label: "Relations",
            items: [{ type: "autogenerated", dirName: "Relations" }],
        },
        {
            type: "category",
            label: "Working with Entity Manager",
            items: [
                {
                    type: "autogenerated",
                    dirName: "Working with Entity Manager",
                },
            ],
        },
        {
            type: "category",
            label: "Query Builder",
            items: [{ type: "autogenerated", dirName: "Query Builder" }],
        },
        "query-runner",
        {
            type: "category",
            label: "Guides",
            items: [{ type: "autogenerated", dirName: "Guides" }],
        },
        {
            type: "category",
            label: "Advanced Topics",
            items: [{ type: "autogenerated", dirName: "Advanced Topics" }],
        },
        {
            type: "category",
            label: "Help",
            items: [{ type: "autogenerated", dirName: "Help" }],
        },
        "future-of-typeorm",
    ],
}

export default sidebars
