import type { MigrationInterface } from "./MigrationInterface"

/**
 * Represents entity of the migration in the database.
 */
export class Migration {
    // -------------------------------------------------------------------------
    // Public Properties
    // -------------------------------------------------------------------------

    /**
     * Migration id.
     * Indicates order of the executed migrations.
     */
    id: number | undefined

    /**
     * Timestamp of the migration.
     */
    timestamp: number

    /**
     * Name of the migration (class name).
     */
    name: string

    /**
     * Migration instance that needs to be run.
     */
    instance?: MigrationInterface

    /**
     * Whether to run this migration within a transaction
     */
    transaction?: boolean

    /**
     * Time the migration row was inserted into the migrations table.
     * Milliseconds since epoch. Undefined for rows created before this column existed.
     */
    executedAt?: number

    /**
     * SHA-256 checksum of the migration name plus SQL generated by `up()`
     * (64-char hex). Undefined for rows created before this column existed,
     * or when the migration was recorded without an instance.
     */
    checksum?: string

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor(
        id: number | undefined,
        timestamp: number,
        name: string,
        instance?: MigrationInterface,
        transaction?: boolean,
        executedAt?: number,
        checksum?: string,
    ) {
        this.id = id
        this.timestamp = timestamp
        this.name = name
        this.instance = instance
        this.transaction = transaction
        this.executedAt = executedAt
        this.checksum = checksum
    }
}
