name: Close Stale Issues

on:
  workflow_dispatch:

jobs:
  close-stale-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 180 # 6 months
          days-before-close: 0
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-message: ""
          close-issue-message: |
            TypeORM has returned to active development after recently transitioning to new leadership ([see related announcement](https://typeorm.io/docs/future-of-typeorm/)).

            As part of the new team's efforts to prioritise work on the project moving forward, it is necessary to clean up the backlog of stale issues.

            🧹 This issue is being automatically closed because it has had no activity in the last 6 months.
            If you believe this issue is still relevant, feel free to comment below and the maintainers may reopen it. Thank you for your contribution.
          stale-issue-label: "stale"
          exempt-issue-labels: "pinned,security"
