name: database-tests

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  oracle:
    # nyc is stuck at the end of the test execution even if all tests pass on Node.js 16.x
    if: ${{ inputs.node-version != 16 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose -f .github/workflows/test/oracle.docker-compose.yml up oracle --detach

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - run: npm i
      - run: cp .github/workflows/test/oracle.ormconfig.json ormconfig.json
      - run: docker compose -f .github/workflows/test/oracle.docker-compose.yml up oracle --wait
      - run: npx nyc npm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: oracle-node:${{ inputs.node-version }}
          parallel: true
