name: database-tests-compose

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  oracle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose up oracle --detach

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - run: npm ci
      - run: cat ormconfig.sample.json | jq 'map(select(.name == "oracle"))' > ormconfig.json
      - run: docker compose up oracle --no-recreate --wait
      - run: npx nyc npm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: oracle-node:${{ inputs.node-version }}
          parallel: true

  sap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: docker compose up hanaexpress --detach

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: build/

      - run: npm i
      - run: cat ormconfig.sample.json | jq 'map(select(.name == "hanaexpress"))' > ormconfig.json
      - run: docker compose up hanaexpress --no-recreate --wait
      - run: npx nyc npm run test:ci

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: sap-node:${{ inputs.node-version }}
          parallel: true
