# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs
# https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers

name: test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["master"]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci
      - run: npm run lint
      - run: npm run format:ci

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - run: npm ci
      - run: npm run compile

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/
          retention-days: 1

  # These tests run in standard node containers with their db attached as a service
  database-tests:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16, 18, 20] #, 22]
    uses: ./.github/workflows/database-tests.yml
    with:
      node-version: ${{matrix.node-version}}

  # These tests run with custom docker image attributes that can't be specified in a GHA service
  database-tests-compose:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18, 20] #, 22]
    uses: ./.github/workflows/database-tests-compose.yml
    with:
      node-version: ${{matrix.node-version}}

  database-tests-windows:
    needs: build
    uses: ./.github/workflows/database-tests-windows.yml

  # Run with most databases possible to provide the coverage of the tests
  coverage:
    if: ${{ always() }}
    needs: [database-tests, database-tests-compose, database-tests-windows]
    uses: ./.github/workflows/coverage.yml
